name         'rji-jboss_as'
version      '1.1.0'
author       'rji'
license      'Apache License, Version 2.0'
summary      'Install, configure, and deploy applications on JBoss AS 7.'
description  'A Puppet module to manage the installation, configuration, and application deployments for JBoss Application Server 7. It is compatible with Enterprise Linux and Ubuntu.'
project_page 'https://github.com/rji/puppet-jboss_as'
